import type { Metadata } from "next";
import "@/app/_styles/globals.css";
import ProtectLayout from "../_components/ProtectLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ProtectLayout>{children}</ProtectLayout>;
}
